name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Upload build artifacts (optional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: |
            .next/**
            !.next/cache/**
            package.json
            next.config.mjs
            prisma/schema.prisma
