name: Deploy (Coolify)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COOLIFY_WEBHOOK_URL: ${{ secrets.COOLIFY_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Coolify Deploy (Webhook)
        run: |
          echo "Triggering Coolify webhook..."
          if [ -n "$COOLIFY_WEBHOOK_URL" ]; then \
            curl -fsSL -X POST "$COOLIFY_WEBHOOK_URL" -H 'Content-Type: application/json' -d '{"event":"push","branch":"main"}'; \
          else \
            echo "COOLIFY_WEBHOOK_URL not set. Skipping webhook."; \
          fi
